name: 'Istio install'
author: 'Deepak Deore'
description: 'Install istio with custom override file'
inputs:
  istio version:
    description: 'Istio version to install'
    required: true
runs:
  using: 'docker'
  image: 'istio/istioctl:${{ inputs.istio version }}'
  args: 
  - 'manifest'
  - 'generate'
