name: 'Istio install'
author: 'Deepak Deore'
description: 'Install istio with custom override file'
inputs:
  istio version:
    description: 'Istio version to install'
    required: true
  override:
    description: 'Istio override file'
    required: true
runs:
  using: 'docker'
  image: 'docker://istio/istioctl:1.6.2'
  #image: 'docker://alpine:3.10'
  args: 
  - 'manifest'
  - 'generate'
  - '-f'
  - /github/workspace/${{ inputs.override }}
